version: '2'
services:
  pytalk:
     build: . 
     
     expose:
        - "9999"
     command: jupyter-notebook --config=/notebooks/config.py
     
     volumes:
           
        - ./books:/jupyter

