version: '3.6'
services:
  jupyter:
     build:
       context: .
       dockerfile: ./binder/Dockerfile
       target: jupyter
     volumes:
       - ./work:${WORK}
     ports:
        - ${PORT}:8888

  r:
    build:
      context: .
      dockerfile: ./binder/Dockerfile-R
      target: r
    volumes:
      - ./work:${WORK}
    ports:
      - 8884:8888

