version: '3.5'
services:
  web:
     build:
       context: .
       dockerfile: ./binder/Dockerfile
     volumes:
       - ./books:/home/jovyan/work
       - ./jupyter_notebook_config.py:/etc/jupyter/jupyter_notebook_config.py:ro
     ports:
        - "9012:8888"