version: '3.6'
services:
  jupyter:
     build:
       context: .
       dockerfile: ./binder/Dockerfile
       target: jupyter
     volumes:
       - ./work:/home/jovyan/work
     ports:
        - 8888:8888

  slides:
    build:
      context: .
      dockerfile: ./binder/Dockerfile
      target: slides
    volumes:
      - ./work:/home/jovyan/work
      - ./slides:/home/jovyan/slides

    user: root
